# Generated by Django 4.0.1 on 2022-04-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estipositions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='price',
            field=models.FloatField(blank=True, default=0.0, help_text='in Rands'),
        ),
        migrations.AddField(
            model_name='position',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, help_text='how many units?'),
        ),
    ]
