# Generated by Django 4.0.1 on 2022-04-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estipositions', '0002_position_price_position_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='amount',
            field=models.FloatField(help_text='in Rands', null=True),
        ),
    ]
