# Generated by Django 4.0.1 on 2022-04-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profiles_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profiles',
            name='company_logo',
            field=models.ImageField(default='logo/no_photo.png', upload_to=''),
        ),
    ]
