# Generated by Django 4.0.1 on 2022-04-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profiles_avatar_profiles_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(default='images/default.png', upload_to=''),
        ),
    ]
