# Generated by Django 4.0.1 on 2022-04-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profiles_company_reg_no_profiles_vat_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
