# Generated by Django 4.0.1 on 2022-04-06 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('clients', '0001_initial'),
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('completion_date', models.DateField()),
                ('issued_date', models.DateField()),
                ('payement_date', models.DateField()),
                ('created', models.DateTimeField()),
                ('closed', models.BooleanField(default=False)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
