# Generated by Django 4.0.1 on 2022-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_invoice_tag_delete_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='completion_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payement_date',
            field=models.DateField(blank=True),
        ),
    ]
