# Generated by Django 4.0.1 on 2022-04-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_alter_invoice_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
