# Generated by Django 4.0.1 on 2022-04-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0006_alter_invoice_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
