# Generated by Django 4.0.1 on 2022-04-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('company_reg_no', models.CharField(blank=True, max_length=20)),
                ('vat_no', models.IntegerField(blank=True, max_length=10)),
                ('logo', models.ImageField(default='images/no_photo.png', upload_to='')),
            ],
        ),
    ]
