# Generated by Django 4.0.1 on 2022-04-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_vat_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
