# Generated by Django 4.0.1 on 2022-04-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
